# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  bind-interface:
    type: string
    description: |
      Local interface to bind for GTP and S1AP connection.
  enb-name:
    type: string
    description: |
      eNodeB name.
    default: dummyENB01
  enb-mcc:
    type: string
    description: |
      EnodeB Mobile Country Code (MCC).
    default: '001'
  enb-mnc:
    type: string
    description: |
      EnodeB Mobile Network Code (MNC).
    default: '01'
  enb-rf-device-name:
    type: string
    description: |
      RF Device Name.
    default: "zmq"
  enb-rf-device-args:
    type: string
    description: |
      RF Device Arguments.
    default: fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://localhost:2001,id=enb,base_srate=23.04e6
  ue-usim-algo:
    type: string
    description: |
      The authentication algorithm to use (MILENAGE or XOR).
    default: milenage
  ue-nas-apn:
    type: string
    description: |
      NAS Access Point Name (APN).
    default: default
  ue-device-name:
    type: string
    description: |
      UE Device Name.
    default: zmq
  ue-device-args:
    type: string
    description: |
      UE Device arguments.
    default: tx_port=tcp://*:2001,rx_port=tcp://localhost:2000,id=ue,base_srate=23.04e6
