# Copyright 2020 David Garcia
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
options:
  bind-address-subnet:
    type: string
    description: |
      The selected bind address will need to be part of this subnet.
      If this is not set, it will use the IP address from the default interface.
    default: ""