name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Promotion process
        options:
          - edge -> beta
          - beta -> candidate
          - candidate -> stable

jobs:
  promote:
    name: Promote Charm
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Set target channel
        env:
          PROMOTION: ${{ github.event.inputs.promotion }}
        run: |
          if [ "${PROMOTION}" == "edge -> beta" ]; then
            echo "promote-from=edge" >> ${GITHUB_ENV}
            echo "promote-to=beta" >> ${GITHUB_ENV}
          elif [ "${PROMOTION}" == "beta -> candidate" ]; then
            echo "promote-from=beta" >> ${GITHUB_ENV}
            echo "promote-to=candidate" >> ${GITHUB_ENV}
          elif [ "${PROMOTION}" == "candidate -> stable" ]; then
            echo "promote-from=candidate" >> ${GITHUB_ENV}
            echo "promote-to=stable" >> ${GITHUB_ENV}
          fi
      - name: Promote Charm
        uses: canonical/charming-actions/release-charm@2.2.2
        with:
          credentials: ${{ secrets.CHARMCRAFT_AUTH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          destination-channel: ${{ env.promote-to }}
          origin-channel: ${{ env.promote-from }}
          charmcraft-channel: ${{ env.CHARMCRAFT_VERSION }}
